CREATE DATABASE IF NOT EXISTS infbot_game;
USE infbot_game;

CREATE TABLE IF NOT EXISTS players (
    userId VARCHAR(32) PRIMARY KEY,
    neocreds INT DEFAULT 0,
    job VARCHAR(50) DEFAULT NULL,
    inventory JSON DEFAULT '[]',
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);